import { createApp } from "vue";
import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/reset.css';
import "./style.css";
import App from "./App.vue";
import router from "./route/index";
import { i18n } from "./plugins/i18n";
const app = createApp(App);
app.use(Antd);
app.use(router);
app.use(i18n);
app.mount("#app");
